name=RohitCore-Base
version=1.0.0
author=Rohit Maji
maintainer=Rohit Maji <rohitmaji2002.com>
sentence=Core utility library for Arduino (debugging, board detection, memory tools)
paragraph=Provides debugging, board detection, and memory utilities for Arduino projects. Designed as the foundation for the RohitCore ecosystem.
category=Other
url=https://github.com/rohitmaji004/RohitCore-Base
architectures=*
